services:
  db:
    image: bitnami/postgresql:latest
    container_name: upload-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=upload
    volumes:
      - './docker:/docker-entrypoint-initdb.d'
      - 'db:/var/lib/postgresql/data'

  app:
    build: .
    depends_on:
      - db
    container_name: fastify-upload
    ports:
      - "8080:8080"
    environment:
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL
      - DATABASE_URL=$DATABASE_URL

volumes:
  db: